# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('nepalfund_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_tagline', models.CharField(default='LETS START FUNDING THE NEW NEPAL.', help_text='The tagline for the site.', max_length=100)),
                ('site_subheading', models.TextField(default="When you donate to nepal fund's projects, you are making a lasting impact on the future of Nepal.", help_text='Sub heading for the site')),
                ('learn_button_text', models.CharField(default='DONATE', help_text="The label on the 'Learn more button'", max_length=50)),
                ('how_it_works_heading', models.CharField(default='How it works', help_text="The heading to display above the 'Learn about how it works' section ", max_length=50)),
                ('how_it_works_intro', models.TextField(default="'What a piece of work is man! how noble in reason! how infinite in faculty! in form and moving how express and admirable! in action how like an angel! in apprehension how like a god! the beauty of the world, the paragon of animals! '. - (Act II, Scene II).", help_text="Intro paragraph for the 'Learn about how it works' section.")),
                ('how_it_works_video_url', models.URLField(default='https://www.youtube.com/embed/MCJGcDDNtms', help_text="URL for 'how it works' video")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
