# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:14
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='How much do you aim to raise for the project?', max_digits=15)),
                ('title', models.CharField(help_text='What would you like to name this project?', max_length=255)),
                ('tagline', models.CharField(help_text='Write a short tag line that describes this project.)', max_length=200, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional: Link to a Youtube or vimeo about the project.', max_length=255, verbose_name='Video URL')),
                ('location', models.CharField(help_text='What is the address of the organization or main site of the project?', max_length=255, verbose_name='Organization Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(help_text='When will this crowdfunding project end?')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('AC', 'Active'), ('ST', 'Staged'), ('CO', 'Completed'), ('DR', 'Drafted')], default='DR', max_length=2)),
                ('cover_photo', imagekit.models.fields.ProcessedImageField(blank=True, default=None, help_text='A high resolution image to represent the project.', upload_to='covers/')),
                ('description', ckeditor.fields.RichTextField(help_text='This is the body of content that shows up on the project page.', verbose_name='Project description')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
