# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by_user',
            new_name='created_by',
        ),
    ]
