# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_for_project', to='project.Project'),
        ),
    ]
